name: Prod Front2 CI

on:
  push:
    branches: [ master ]
    paths:
      - "front2/**"
      - ".github/workflows/front2_production.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "front2/**"
      - ".github/workflows/front2_production.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install, build, and test
      run: |
        cd front2 && yarn install
        yarn build
        yarn test
    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_2_ID }}
      with:
        args: deploy --dir=build --prod
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
