name: Dev Front1 CI

on:
  push:
    branches:
      - 'develop'
    paths:
      - "front1/**"
      - ".github/workflows/front1_staging.yml"
  pull_request:
    branches:
      - 'develop'
    paths:
      - "front1/**"
      - ".github/workflows/front1_staging.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: yarn install, build, and test
      run: |
        cd front1
        yarn install
        yarn release
        yarn test
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: staging
        sourcemaps: ./front1/build
    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
      with:
        args: deploy --dir="front1/build" --prod
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
